paths:
  /api/post:
    post:
      security:
        - jwt: []
      tags:
        - Post
      summary: Create new Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                breed:
                  type: string
                image:
                  type: string(base64)
                lat:
                  type: float
                lng:
                  type: float
                gender:
                  type: string
                  oneOf:
                    - MALE
                    - FEMALE
              example:
                description: some crazy dog is wandering around.. send help
                breed: bulldog
                gender: FEMALE
                lat: 50.4547
                lng: 30.5238
      responses:
        '200':
          description: Post object
          content:
            application/json:
              schema:
                type: object
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    get:
      security:
        - jwt: []
      tags:
        - Post
      summary: Get all Posts
      parameters:
        - in: query
          name: userId
          schema:
            type: integer
          description: User ID
      responses:
        '200':
          description: List with all Post objectecs
          content:
            application/json:
              schema:
                $ref: '#/components/models/Post'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/post/{postId}:
    delete:
      security:
        - jwt: []
      tags:
        - Post
      summary: Delete post by id
      parameters:
        - in: path
          name: postId # Note the name is the same as in the path
          required: true
          schema:
            type: integer
          description: Post ID
components:
  schemas:
    Post:
      type: object
      properties:
        description:
          type: string
        breed:
          type: string
        image:
          type: string(base64)
        lat:
          type: float
        lng:
          type: float
        gender:
          type: string
          oneOf:
            - MALE
            - FEMALE
        createdAt:
          type: date
        updateddAt:
          type: date
